name: Bug Report - Web
description: Wolvesville for Web - Bug Report
labels: ["Web"]
body:
  - type: textarea
    id: what
    attributes:
      label: Description
      description: Compare what's supposed to happen to what's happening. When does this happen. As precise as possible. You can use [markdown](https://learnxinyminutes.com/docs/markdown/)
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Report author
      placeholder: DiscordID e.g. 364096171997921280
  - type: input
    id: version
    attributes:
      label: Game version
      placeholder: e.g. 1.9.7
  - type: input
    id: browser
    attributes:
      label: Browser / Version
      placeholder: e.g. Firefox 96.0.1